- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 13:07:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mesas` (
  `idMesa` INT NOT NULL,
  `numeroMesa` VARCHAR(45) NULL,
  `capacidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `fecha` DATE NULL,
  `estadoPedido` VARCHAR(45) NULL,
  `Mesas_idMesa` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Mesas1_idx` (`Mesas_idMesa` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Mesas1`
    FOREIGN KEY (`Mesas_idMesa`)
    REFERENCES `mydb`.`Mesas` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleado` INT NOT NULL,
  `nombre` INT NULL,
  `apellido` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `salario` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `Jefe` VARCHAR(45) NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Jefe`),
  INDEX `fk_Empleados_Empleados_idx` (`Jefe` ASC) VISIBLE,
  INDEX `fk_Empleados_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Empleados`
    FOREIGN KEY (`Jefe`)
    REFERENCES `mydb`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idPlato` INT NOT NULL,
  `nombrePlato` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallesPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DetallesPedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DetallesPedido` (
  `Pedido_idPedido` INT NOT NULL,
  `Producto_idPlato` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Producto_idPlato`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`Producto_idPlato` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idPlato`)
    REFERENCES `mydb`.`Productos` (`idPlato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idMenu` INT NOT NULL,
  `nombreMenu` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallesMenu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DetallesMenu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DetallesMenu` (
  `Menu_idMenu` INT NOT NULL,
  `Productos_idPlato` INT NOT NULL,
  PRIMARY KEY (`Menu_idMenu`, `Productos_idPlato`),
  INDEX `fk_Menu_has_Productos_Productos1_idx` (`Productos_idPlato` ASC) VISIBLE,
  INDEX `fk_Menu_has_Productos_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_has_Productos_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idPlato`)
    REFERENCES `mydb`.`Productos` (`idPlato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TABLE_NAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TABLE_NAME` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TABLE_NAME` (
  `id_plato` INT(11) NULL DEFAULT NULL,
  `nombrePlato` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
